pipeline {
    agent any
    environment {
        PATH = "/opt/homebrew/bin/npm"
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
    }
}
